dist: bionic
language: go
go:
- 1.13.x

jobs:
  include:
    - name: Unit Tests
      stage: test
      script: make test verbose=true
    - name: E2E Tests
      stage: test
      script: make functional
      services:
        - docker
    - stage: tag
      script: make tag
      if: branch = master AND type = push
